#-------------------------------------------------
#
# Project created by QtCreator 2012-10-20T23:25:29
#
#-------------------------------------------------

QT += gui

TARGET = sword
TEMPLATE = lib
CONFIG += staticlib

INCLUDEPATH += . \
    ../../../../sword/include \
    ../../../../sword/include/internal/regex

SOURCES += \
    ../../../../sword/src/modules/common/zipcomprs.cpp \
    ../../../../sword/src/utilfuns/zlib/untgz.c \
    ../../../../sword/src/utilfuns/zlib/gzio.c \
    ../../../../sword/src/utilfuns/zlib/zutil.c \
    ../../../../sword/src/utilfuns/zlib/uncompr.c \
    ../../../../sword/src/utilfuns/zlib/trees.c \
    ../../../../sword/src/utilfuns/zlib/maketree.c \
    ../../../../sword/src/utilfuns/zlib/infutil.c \
    ../../../../sword/src/utilfuns/zlib/inftrees.c \
    ../../../../sword/src/utilfuns/zlib/inflate.c \
    ../../../../sword/src/utilfuns/zlib/inffast.c \
    ../../../../sword/src/utilfuns/zlib/infcodes.c \
    ../../../../sword/src/utilfuns/zlib/infblock.c \
    ../../../../sword/src/utilfuns/zlib/deflate.c \
    ../../../../sword/src/utilfuns/zlib/crc32.c \
    ../../../../sword/src/utilfuns/zlib/compress.c \
    ../../../../sword/src/utilfuns/zlib/adler32.c \
    ../../../../sword/src/mgr/ftplibftpt.cpp \
    ../../../../sword/src/utilfuns/ftplib.c \
    ../../../../sword/src/utilfuns/regex.c \
    ../../../../sword/src/frontend/swdisp.cpp \
    ../../../../sword/src/frontend/swlog.cpp \
    ../../../../sword/src/keys/swkey.cpp \
    ../../../../sword/src/keys/listkey.cpp \
    ../../../../sword/src/keys/strkey.cpp \
    ../../../../sword/src/keys/treekey.cpp \
    ../../../../sword/src/keys/treekeyidx.cpp \
    ../../../../sword/src/keys/versekey.cpp \
    ../../../../sword/src/keys/versetreekey.cpp \
    ../../../../sword/src/mgr/swconfig.cpp \
    ../../../../sword/src/mgr/swmgr.cpp \
    ../../../../sword/src/mgr/swfiltermgr.cpp \
    ../../../../sword/src/mgr/encfiltmgr.cpp \
    ../../../../sword/src/mgr/markupfiltmgr.cpp \
    ../../../../sword/src/mgr/filemgr.cpp \
    ../../../../sword/src/mgr/versemgr.cpp \
    ../../../../sword/src/mgr/ftptrans.cpp \
    ../../../../sword/src/mgr/swlocale.cpp \
    ../../../../sword/src/mgr/localemgr.cpp \
    ../../../../sword/src/mgr/swcacher.cpp \
    ../../../../sword/src/mgr/swsearchable.cpp \
    ../../../../sword/src/mgr/installmgr.cpp \
    ../../../../sword/src/mgr/stringmgr.cpp \
    ../../../../sword/src/modules/swmodule.cpp \
    ../../../../sword/src/modules/comments/swcom.cpp \
    ../../../../sword/src/modules/comments/hrefcom/hrefcom.cpp \
    ../../../../sword/src/modules/comments/rawcom/rawcom.cpp \
    ../../../../sword/src/modules/comments/rawcom4/rawcom4.cpp \
    ../../../../sword/src/modules/comments/rawfiles/rawfiles.cpp \
    ../../../../sword/src/modules/comments/zcom/zcom.cpp \
    ../../../../sword/src/modules/common/rawstr.cpp \
    ../../../../sword/src/modules/common/rawstr4.cpp \
    ../../../../sword/src/modules/common/swcomprs.cpp \
    ../../../../sword/src/modules/common/lzsscomprs.cpp \
    ../../../../sword/src/modules/common/rawverse.cpp \
    ../../../../sword/src/modules/common/rawverse4.cpp \
    ../../../../sword/src/modules/common/swcipher.cpp \
    ../../../../sword/src/modules/common/zverse.cpp \
    ../../../../sword/src/modules/common/zstr.cpp \
    ../../../../sword/src/modules/common/entriesblk.cpp \
    ../../../../sword/src/modules/common/sapphire.cpp \
    ../../../../sword/src/modules/filters/swbasicfilter.cpp \
    ../../../../sword/src/modules/filters/swoptfilter.cpp \
    ../../../../sword/src/modules/filters/gbfhtml.cpp \
    ../../../../sword/src/modules/filters/gbfxhtml.cpp \
    ../../../../sword/src/modules/filters/gbfhtmlhref.cpp \
    ../../../../sword/src/modules/filters/gbfwebif.cpp \
    ../../../../sword/src/modules/filters/gbfplain.cpp \
    ../../../../sword/src/modules/filters/gbfrtf.cpp \
    ../../../../sword/src/modules/filters/gbfstrongs.cpp \
    ../../../../sword/src/modules/filters/gbffootnotes.cpp \
    ../../../../sword/src/modules/filters/gbfheadings.cpp \
    ../../../../sword/src/modules/filters/gbfredletterwords.cpp \
    ../../../../sword/src/modules/filters/gbfmorph.cpp \
    ../../../../sword/src/modules/filters/gbfwordjs.cpp \
    ../../../../sword/src/modules/filters/thmlstrongs.cpp \
    ../../../../sword/src/modules/filters/thmlfootnotes.cpp \
    ../../../../sword/src/modules/filters/thmlheadings.cpp \
    ../../../../sword/src/modules/filters/thmlmorph.cpp \
    ../../../../sword/src/modules/filters/thmllemma.cpp \
    ../../../../sword/src/modules/filters/thmlscripref.cpp \
    ../../../../sword/src/modules/filters/thmlvariants.cpp \
    ../../../../sword/src/modules/filters/thmlgbf.cpp \
    ../../../../sword/src/modules/filters/thmlrtf.cpp \
    ../../../../sword/src/modules/filters/thmlhtml.cpp \
    ../../../../sword/src/modules/filters/thmlxhtml.cpp \
    ../../../../sword/src/modules/filters/thmlhtmlhref.cpp \
    ../../../../sword/src/modules/filters/thmlwebif.cpp \
    ../../../../sword/src/modules/filters/thmlwordjs.cpp \
    ../../../../sword/src/modules/filters/teiplain.cpp \
    ../../../../sword/src/modules/filters/teirtf.cpp \
    ../../../../sword/src/modules/filters/teihtmlhref.cpp \
    ../../../../sword/src/modules/filters/gbfthml.cpp \
    ../../../../sword/src/modules/filters/gbfosis.cpp \
    ../../../../sword/src/modules/filters/thmlosis.cpp \
    ../../../../sword/src/modules/filters/thmlplain.cpp \
    ../../../../sword/src/modules/filters/osisosis.cpp \
    ../../../../sword/src/modules/filters/osisheadings.cpp \
    ../../../../sword/src/modules/filters/osisfootnotes.cpp \
    ../../../../sword/src/modules/filters/osishtmlhref.cpp \
    ../../../../sword/src/modules/filters/osisxhtml.cpp \
    ../../../../sword/src/modules/filters/osiswebif.cpp \
    ../../../../sword/src/modules/filters/osismorph.cpp \
    ../../../../sword/src/modules/filters/osisstrongs.cpp \
    ../../../../sword/src/modules/filters/osisplain.cpp \
    ../../../../sword/src/modules/filters/osisrtf.cpp \
    ../../../../sword/src/modules/filters/osislemma.cpp \
    ../../../../sword/src/modules/filters/osisredletterwords.cpp \
    ../../../../sword/src/modules/filters/osisscripref.cpp \
    ../../../../sword/src/modules/filters/osisvariants.cpp \
    ../../../../sword/src/modules/filters/osiswordjs.cpp \
    ../../../../sword/src/modules/filters/osismorphsegmentation.cpp \
    ../../../../sword/src/modules/filters/osisruby.cpp \
    ../../../../sword/src/modules/filters/latin1utf8.cpp \
    ../../../../sword/src/modules/filters/latin1utf16.cpp \
    ../../../../sword/src/modules/filters/utf8utf16.cpp \
    ../../../../sword/src/modules/filters/utf16utf8.cpp \
    ../../../../sword/src/modules/filters/utf8html.cpp \
    ../../../../sword/src/modules/filters/utf8latin1.cpp \
    ../../../../sword/src/modules/filters/utf8cantillation.cpp \
    ../../../../sword/src/modules/filters/utf8hebrewpoints.cpp \
    ../../../../sword/src/modules/filters/utf8arabicpoints.cpp \
    ../../../../sword/src/modules/filters/utf8greekaccents.cpp \
    ../../../../sword/src/modules/filters/cipherfil.cpp \
    ../../../../sword/src/modules/filters/rtfhtml.cpp \
    ../../../../sword/src/modules/filters/plainfootnotes.cpp \
    ../../../../sword/src/modules/filters/plainhtml.cpp \
    ../../../../sword/src/modules/filters/greeklexattribs.cpp \
    ../../../../sword/src/modules/filters/unicodertf.cpp \
    ../../../../sword/src/modules/filters/papyriplain.cpp \
    ../../../../sword/src/modules/genbook/swgenbook.cpp \
    ../../../../sword/src/modules/genbook/rawgenbook/rawgenbook.cpp \
    ../../../../sword/src/modules/lexdict/swld.cpp \
    ../../../../sword/src/modules/lexdict/rawld/rawld.cpp \
    ../../../../sword/src/modules/lexdict/rawld4/rawld4.cpp \
    ../../../../sword/src/modules/lexdict/zld/zld.cpp \
    ../../../../sword/src/modules/texts/swtext.cpp \
    ../../../../sword/src/modules/texts/rawtext/rawtext.cpp \
    ../../../../sword/src/modules/texts/rawtext4/rawtext4.cpp \
    ../../../../sword/src/modules/texts/ztext/ztext.cpp \
    ../../../../sword/src/utilfuns/swobject.cpp \
    ../../../../sword/src/utilfuns/utilstr.cpp \
    ../../../../sword/src/utilfuns/utilxml.cpp \
    ../../../../sword/src/utilfuns/swunicod.cpp \
    ../../../../sword/src/utilfuns/swversion.cpp \
    ../../../../sword/src/utilfuns/swbuf.cpp \
    ../../../../sword/src/utilfuns/ftpparse.c \
    ../../../../sword/src/utilfuns/url.cpp \
    ../../../../sword/src/utilfuns/roman.cpp

OTHER_FILES += \
    android/AndroidManifest.xml \
    android/res/drawable/icon.png \
    android/res/drawable/logo.png \
    android/res/drawable-hdpi/icon.png \
    android/res/drawable-ldpi/icon.png \
    android/res/drawable-mdpi/icon.png \
    android/res/layout/splash.xml \
    android/res/values/libs.xml \
    android/res/values/strings.xml \
    android/res/values-de/strings.xml \
    android/res/values-el/strings.xml \
    android/res/values-es/strings.xml \
    android/res/values-et/strings.xml \
    android/res/values-fa/strings.xml \
    android/res/values-fr/strings.xml \
    android/res/values-id/strings.xml \
    android/res/values-it/strings.xml \
    android/res/values-ja/strings.xml \
    android/res/values-ms/strings.xml \
    android/res/values-nb/strings.xml \
    android/res/values-nl/strings.xml \
    android/res/values-pl/strings.xml \
    android/res/values-pt-rBR/strings.xml \
    android/res/values-ro/strings.xml \
    android/res/values-rs/strings.xml \
    android/res/values-ru/strings.xml \
    android/res/values-zh-rCN/strings.xml \
    android/res/values-zh-rTW/strings.xml \
    android/src/org/kde/necessitas/ministro/IMinistro.aidl \
    android/src/org/kde/necessitas/ministro/IMinistroCallback.aidl \
    android/src/org/kde/necessitas/origo/QtActivity.java \
    android/src/org/kde/necessitas/origo/QtApplication.java \
    android/version.xml \
    android/AndroidManifest.xml \
    android/res/drawable/icon.png \
    android/res/drawable/logo.png \
    android/res/drawable-hdpi/icon.png \
    android/res/drawable-ldpi/icon.png \
    android/res/drawable-mdpi/icon.png \
    android/res/layout/splash.xml \
    android/res/values/libs.xml \
    android/res/values/strings.xml \
    android/res/values-de/strings.xml \
    android/res/values-el/strings.xml \
    android/res/values-es/strings.xml \
    android/res/values-et/strings.xml \
    android/res/values-fa/strings.xml \
    android/res/values-fr/strings.xml \
    android/res/values-id/strings.xml \
    android/res/values-it/strings.xml \
    android/res/values-ja/strings.xml \
    android/res/values-ms/strings.xml \
    android/res/values-nb/strings.xml \
    android/res/values-nl/strings.xml \
    android/res/values-pl/strings.xml \
    android/res/values-pt-rBR/strings.xml \
    android/res/values-ro/strings.xml \
    android/res/values-rs/strings.xml \
    android/res/values-ru/strings.xml \
    android/res/values-zh-rCN/strings.xml \
    android/res/values-zh-rTW/strings.xml \
    android/src/org/kde/necessitas/ministro/IMinistro.aidl \
    android/src/org/kde/necessitas/ministro/IMinistroCallback.aidl \
    android/src/org/kde/necessitas/origo/QtActivity.java \
    android/src/org/kde/necessitas/origo/QtApplication.java \
    android/version.xml
